---
# tasks list to add ppa for firefox on Ubuntu, because of course they don't include the ESR build either...
- name: Firefox | Install | Ubuntu
  become: true
  community.general.snap:
    name: "{{ firefox_install_ubuntu }}"
