---
# tasks list for cloning private git repos
- name: Git | Clone | Private Repos
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('master') }}"
    depth: 1
    force: true
    key_file: "{{ git_key_file }}"
    accept_newhostkey: true
  loop: "{{ private_repos | default([]) }}"
  when: item.repo is defined
